#!/usr/bin/env python3
"""Generate review-candidate Azure Terraform roots from the migration blueprint.

Standards this emitter aims for (realistic, not perfect fidelity):
- Microsoft CAF naming abbreviations (rg-, vnet-, snet-, nsg-, st, id-, vmss-, ...)
- Azure Well-Architected security defaults: TLS1.2+, HTTPS-only storage, SSH-only compute
  (no password defaults in git), private blob containers
- HashiCorp/OpenTofu root layout: versions/providers/variables/outputs + .gitignore
- Honest emission labels from azure_mapping_catalog (mapped ≠ full equivalent)

This is review-candidate IaC: safe to open a PR and inspect. It is not apply-ready
landing-zone / AVM composition for every AWS service.
"""

from __future__ import annotations

import json
import re
import shutil
import sys
import textwrap
from pathlib import Path

# Script-pack helpers (app_iam.py) live beside this file under $WORK_ROOT/scripts.
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

PLACEHOLDER_SSH_PUBKEY = (
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDu+F2KA+8AwzD9H8iJXO37rAD35pgzahB5DLNFWicc9 "
    "REPLACE-BEFORE-APPLY@stackgen-aws-migrator"
)

STANDARDS_HEADER = """# Review-candidate Azure root generated by StackGen aws-migrator.
# Standards: Microsoft CAF naming, Azure WAF security defaults (TLS1.2+, HTTPS-only storage,
# SSH-only Linux compute), OpenTofu/HashiCorp root layout. Not full Azure Verified Modules (AVM).
# Do not apply until operators replace placeholders and complete review-needed items.
"""

FULL_SCAFFOLD_CATEGORIES = {
    "network",
    "kubernetes",
    "vmss",
    "vm",
    "function",
    "storage",
    "database_postgres",
    "database_nosql",
    "queue",
    "event",
    "dns",
    "cache",
    "observability",
    "containers",
    "cdn",
    "load_balancer",
    "static_ip",
    "api",
}

SOURCE_COVERAGE_THRESHOLD = 0.90
INFRA_CATEGORIES = set(FULL_SCAFFOLD_CATEGORIES)

# Markers used to decide whether a generated root satisfied a category.
CATEGORY_AZURE_MARKERS = {
    "network": ("azurerm_virtual_network", "azurerm_subnet", "azurerm_network_security_group"),
    "storage": ("azurerm_storage_account",),
    "vm": ("azurerm_linux_virtual_machine", "azurerm_windows_virtual_machine"),
    "vmss": ("azurerm_linux_virtual_machine_scale_set", "azurerm_windows_virtual_machine_scale_set"),
    "function": ("azurerm_linux_function_app", "azurerm_windows_function_app"),
    "database_postgres": ("azurerm_postgresql_",),
    "database_nosql": ("azurerm_cosmosdb_",),
    "queue": ("azurerm_servicebus_", "azurerm_storage_queue"),
    "event": ("azurerm_eventhub_", "azurerm_eventgrid_"),
    "dns": ("azurerm_dns_", "azurerm_private_dns_"),
    "cache": ("azurerm_redis_",),
    "kubernetes": ("azurerm_kubernetes_cluster",),
    "containers": ("azurerm_container_app", "azurerm_container_group"),
    "cdn": ("azurerm_cdn_",),
    "load_balancer": ("azurerm_lb", "azurerm_application_gateway"),
    "static_ip": ("azurerm_public_ip",),
    "api": ("azurerm_api_management",),
    "observability": ("azurerm_log_analytics_", "azurerm_monitor_"),
    # Acquisition app-IAM: UAI alone is not enough — custom role definition must land too.
    "identity": ("azurerm_user_assigned_identity",),
}


def safe_name(value, max_len=48):
    value = re.sub(r"[^a-z0-9-]+", "-", (value or "group").lower()).strip("-")
    return (value[:max_len].strip("-") or "group")


def hcl_string(value):
    return json.dumps(str(value))


def hcl_string_map(mapping: dict) -> str:
    """Render a map(string) default without breaking textwrap.dedent on parent templates.

    A bare `{` line in a multi-line map destroys textwrap.dedent's common prefix,
    leaving empty-group variables.tf fmt-dirty. Single-line maps stay indent-safe.
    """
    if not mapping:
        return "{}"
    inner = ", ".join(
        f"{hcl_string(key)} = {hcl_string(value)}" for key, value in sorted(mapping.items())
    )
    return "{ " + inner + " }"


def write_file(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).lstrip() + "\n", encoding="utf-8")


def _azure_resource_type_counts_in_main(main_lines: list[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for line in main_lines:
        m = re.search(r'resource\s+"(azurerm_[^"]+)"\s+"', line)
        if m:
            counts[m.group(1)] = counts.get(m.group(1), 0) + 1
    return counts


def _azure_resource_types_in_main(main_lines: list[str]) -> set[str]:
    return set(_azure_resource_type_counts_in_main(main_lines))



def _consume_mapped_target_instance(remaining: dict[str, int], decision: dict) -> str | None:
    """Consume one actually-emitted target resource assigned by the catalog."""
    candidates = []
    default_target = decision.get("default_target")
    declared_targets = decision.get("target_resource_types") or []
    targets = [default_target] if default_target else declared_targets or decision.get("companions") or []
    for target in targets:
        if isinstance(target, str) and target.startswith("azurerm_") and target not in candidates:
            candidates.append(target)
    for target in candidates:
        if remaining.get(target, 0) > 0:
            remaining[target] -= 1
            return target
    return None

def _coverage_rate(converted: int, applicable: int) -> float | None:
    """Return source-instance coverage; non-applicable rows stay outside the denominator."""
    return round(converted / applicable, 4) if applicable else None


def _coverage_ok(converted: int, applicable: int) -> bool:
    rate = _coverage_rate(converted, applicable)
    return rate is not None and rate >= SOURCE_COVERAGE_THRESHOLD


def _category_satisfied(category: str, azure_types: set[str]) -> bool:
    markers = CATEGORY_AZURE_MARKERS.get(category) or ()
    if not markers:
        return any(t != "azurerm_user_assigned_identity" for t in azure_types)
    for marker in markers:
        for atype in azure_types:
            if atype == marker or atype.startswith(marker):
                return True
    return False


def _count_aws_instances(work: Path) -> dict[str, dict[str, int]]:
    """Return {group_id: {aws_type: instance_count}} from groups/*/terraform.tfstate."""
    out: dict[str, dict[str, int]] = {}
    groups_dir = work / "groups"
    if not groups_dir.is_dir():
        raise ValueError("no AWS source groups found for Azure coverage accounting")
    state_paths = sorted(groups_dir.glob("*/terraform.tfstate"))
    if not state_paths:
        raise ValueError("no AWS source terraform.tfstate files found for Azure coverage accounting")
    for state_path in state_paths:
        group_id = state_path.parent.name
        try:
            state = json.loads(state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"cannot read AWS source state {state_path}: {exc}") from exc
        counts: dict[str, int] = {}
        for resource in state.get("resources") or []:
            if resource.get("mode") != "managed":
                continue
            rtype = str(resource.get("type") or "")
            if not rtype.startswith("aws_"):
                continue
            n = len(resource.get("instances") or [1])
            counts[rtype] = counts.get(rtype, 0) + n
        out[group_id] = counts
    return out


def _compute_infra_conversion(
    work: Path,
    group_azure_types: dict[str, set[str]],
    group_decisions: dict[str, list],
    group_azure_type_counts: dict[str, dict[str, int]] | None = None,
) -> dict:
    """Instance-weighted infra + app-IAM conversion metrics for Azure destination."""
    try:
        from azure_mapping_catalog import load_catalog, resolve
    except ImportError:
        sys.path.insert(0, str((work / "scripts").resolve()))
        from azure_mapping_catalog import load_catalog, resolve  # type: ignore

    catalog_path = work / "scripts" / "mappings" / "aws-to-azure.json"
    if not catalog_path.is_file():
        catalog_path = Path(__file__).resolve().parent.parent / "mappings" / "aws-to-azure.json"
    catalog = load_catalog(catalog_path)

    aws_by_group = _count_aws_instances(work)
    eligible = 0
    converted = 0
    identity_instances = 0
    app_iam_eligible = 0
    app_iam_converted = 0
    applicable = 0
    applicable_converted = 0
    non_applicable_instances = 0
    unsupported_instances = 0
    gaps: list[dict] = []
    gap_keys: set[tuple[str, str]] = set()
    app_iam_types = {"aws_iam_role", "aws_iam_policy", "aws_iam_role_policy"}

    def _append_gap(raw_group_id: str, source_type: str, count: int, **extra) -> None:
        gid = safe_name(raw_group_id)
        key = (gid, source_type)
        if key in gap_keys:
            return
        gap_keys.add(key)
        row = {"group_id": gid, "source_type": source_type, "count": count}
        row.update(extra)
        gaps.append(row)

    group_ids = set(aws_by_group) | set(group_decisions)
    for group_id in sorted(group_ids):
        gid = safe_name(group_id)
        remaining = dict((group_azure_type_counts or {}).get(gid, {}))
        decisions_by_type = {
            d.get("source_type"): d for d in (group_decisions.get(group_id) or []) if d.get("source_type")
        }
        type_counts = aws_by_group.get(group_id) or {src: 1 for src in decisions_by_type}
        for source_type, count in sorted(type_counts.items()):
            decision = decisions_by_type.get(source_type) or resolve(catalog, source_type)
            status = decision.get("status") or "unsupported"
            category = decision.get("category") or "placeholder"
            if status == "non_applicable" or category == "non_applicable":
                non_applicable_instances += count
                continue

            applicable += count
            eligible += count
            identity_source = source_type in app_iam_types or category == "identity"
            if identity_source:
                identity_instances += count
                app_iam_eligible += count
            target = decision.get("default_target")
            if source_type == "aws_iam_role":
                target = "azurerm_user_assigned_identity"
            elif source_type in {"aws_iam_policy", "aws_iam_role_policy"}:
                target = "azurerm_role_definition"

            covered = 0
            if status == "mapped" and isinstance(target, str) and target.startswith("azurerm_"):
                covered = min(count, remaining.get(target, 0))
                remaining[target] = remaining.get(target, 0) - covered
            converted += covered
            applicable_converted += covered
            if identity_source:
                app_iam_converted += covered
            if covered < count:
                if status != "mapped" or not isinstance(target, str):
                    unsupported_instances += count - covered
                reason = "unmapped_source_type" if status != "mapped" else "target_resource_instance_missing"
                _append_gap(group_id, source_type, count - covered, status=status, category=category,
                            emission=decision.get("emission"), reason=reason, target_resource_type=target)

    rate = round(converted / eligible, 4) if eligible else 0.0
    app_rate = round(app_iam_converted / app_iam_eligible, 4) if app_iam_eligible else None
    source_coverage_rate = _coverage_rate(applicable_converted, applicable)
    source_coverage_ok = _coverage_ok(applicable_converted, applicable)
    return {
        "infra_eligible_count": eligible,
        "infra_converted_count": converted,
        "infra_conversion_rate": rate,
        "infra_conversion_ok": eligible > 0 and rate >= SOURCE_COVERAGE_THRESHOLD,
        "source_coverage_applicable_count": applicable,
        "source_coverage_converted_count": applicable_converted,
        "source_coverage_rate": source_coverage_rate,
        "source_coverage_threshold": SOURCE_COVERAGE_THRESHOLD,
        "source_coverage_ok": source_coverage_ok,
        "source_non_applicable_count": non_applicable_instances,
        "source_unsupported_count": unsupported_instances,
        "source_instance_count": applicable + non_applicable_instances,
        "identity_scaffold_count": identity_instances,
        "app_iam_eligible_count": app_iam_eligible,
        "app_iam_converted_count": app_iam_converted,
        "app_iam_conversion_rate": app_rate,
        "app_iam_conversion_threshold": SOURCE_COVERAGE_THRESHOLD,
        "app_iam_conversion_ok": app_iam_eligible > 0 and app_rate is not None and app_rate >= SOURCE_COVERAGE_THRESHOLD,
        "infra_conversion_gaps": gaps[:80],
    }


def generate(work: Path) -> dict:
    azure_root = work / "azure"
    groups_root = azure_root / "groups"
    artifacts = azure_root / "artifacts"
    blueprint = json.loads((artifacts / "migration-blueprint.json").read_text(encoding="utf-8"))
    profile = blueprint["profile"]
    defaults = profile.get("defaults") or {}
    networking = defaults.get("networking") or {}
    vnet_cidr = networking.get("vnet_cidr") or "10.0.0.0/16"
    subnet_cidr = networking.get("subnet_cidr") or "10.0.1.0/24"
    sku = defaults.get("sku") or {}

    if groups_root.exists():
        shutil.rmtree(groups_root)
    groups_root.mkdir(parents=True, exist_ok=True)

    mapping_decisions = {}
    summary_groups = []
    emission_counts = {}
    group_azure_types: dict[str, set[str]] = {}
    group_azure_type_counts: dict[str, dict[str, int]] = {}
    group_decisions_by_id: dict[str, list] = {}

    for group in blueprint["groups"]:
        group_id = safe_name(group["group_id"])
        raw_group_id = group["group_id"]
        stable = group["stable_hash"]
        categories = set(group.get("target_categories") or [])
        decisions = group.get("mapping_decisions") or []
        group_decisions_by_id[raw_group_id] = decisions
        companions = set()
        emissions = set()
        for decision in decisions:
            for companion in decision.get("companions") or []:
                companions.add(companion)
            emissions.add(decision.get("emission") or "resource_group_only")
        for em in emissions:
            emission_counts[em] = emission_counts.get(em, 0) + 1

        root = groups_root / group_id
        root.mkdir(parents=True, exist_ok=True)

        needs_network = bool(
            categories
            & {"network", "kubernetes", "vmss", "vm", "function", "database_postgres", "load_balancer", "containers", "cache"}
        )
        needs_identity = bool(categories & {"identity", "kubernetes", "vmss", "vm", "function", "database_postgres", "containers"})
        needs_storage = bool(categories & {"storage", "function"})
        needs_function_storage = "function" in categories and "storage" not in categories
        needs_storage_container = "azurerm_storage_container" in companions and (needs_storage or needs_function_storage)
        needs_managed_disk = any(d.get("default_target") == "azurerm_managed_disk" for d in decisions)
        storage_name = f"st{stable}"[:24]
        function_storage_name = f"fnst{stable}"[:24]

        write_file(
            root / "versions.tf",
            """
      terraform {
        required_version = ">= 1.6.0"

        required_providers {
          azurerm = {
            source  = "hashicorp/azurerm"
            version = "~> 3.117"
          }
          random = {
            source  = "hashicorp/random"
            version = "~> 3.6"
          }
        }
      }
    """,
        )

        write_file(
            root / "providers.tf",
            """
      provider "azurerm" {
        features {}
      }
    """,
        )

        tags = {
            **(defaults.get("tags") or {}),
            "migration_group": group_id,
            "standards": "caf-waf-review-candidate",
        }
        tags_hcl = hcl_string_map(tags)
        write_file(
            root / "variables.tf",
            f"""
      variable "location" {{
        description = "Azure region (CAF: prefer landing-zone default)."
        type        = string
        default     = {hcl_string(defaults.get("location") or "eastus")}
      }}

      variable "resource_group_name" {{
        description = "CAF resource group name for this migration group."
        type        = string
        default     = {hcl_string("rg-" + group_id[:54])}
      }}

      variable "tags" {{
        description = "Resource tags (include cost center / owner before apply)."
        type        = map(string)
        default     = {tags_hcl}
      }}

      variable "vnet_address_space" {{
        description = "VNet CIDR list. Replace with enterprise IPAM allocations before apply."
        type        = list(string)
        default     = [{hcl_string(vnet_cidr)}]
      }}

      variable "subnet_address_prefixes" {{
        description = "Default subnet prefixes. Replace with enterprise IPAM allocations before apply."
        type        = list(string)
        default     = [{hcl_string(subnet_cidr)}]
      }}

      variable "admin_username" {{
        description = "Linux admin username (WAF: no password auth)."
        type        = string
        default     = "azureuser"
      }}

      variable "admin_ssh_public_key" {{
        description = "SSH public key. Placeholder is public-only and MUST be replaced before apply."
        type        = string
        default     = {hcl_string(PLACEHOLDER_SSH_PUBKEY)}
      }}
    """,
        )

        main = [STANDARDS_HEADER.rstrip(), ""]
        main.append('resource "azurerm_resource_group" "this" {')
        main.append("  name     = var.resource_group_name")
        main.append("  location = var.location")
        main.append("  tags     = var.tags")
        main.append("}")
        main.append("")

        if needs_network:
            main.extend(
                [
                    'resource "azurerm_virtual_network" "this" {',
                    f'  name                = "vnet-{group_id[:55]}"',
                    "  address_space       = var.vnet_address_space",
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  tags                = var.tags",
                    "}",
                    "",
                    'resource "azurerm_subnet" "default" {',
                    '  name                 = "snet-default"',
                    "  resource_group_name  = azurerm_resource_group.this.name",
                    "  virtual_network_name = azurerm_virtual_network.this.name",
                    "  address_prefixes     = var.subnet_address_prefixes",
                    "}",
                    "",
                    'resource "azurerm_network_security_group" "this" {',
                    f'  name                = "nsg-{group_id[:55]}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  tags                = var.tags",
                    "",
                    "  # WAF baseline: deny inbound from Internet by default; open explicitly after review.",
                    '  security_rule {',
                    '    name                       = "deny-internet-inbound"',
                    "    priority                   = 4096",
                    '    direction                  = "Inbound"',
                    '    access                     = "Deny"',
                    '    protocol                   = "*"',
                    '    source_port_range          = "*"',
                    '    destination_port_range     = "*"',
                    '    source_address_prefix      = "Internet"',
                    '    destination_address_prefix = "*"',
                    "  }",
                    "}",
                    "",
                    'resource "azurerm_subnet_network_security_group_association" "default" {',
                    "  subnet_id                 = azurerm_subnet.default.id",
                    "  network_security_group_id = azurerm_network_security_group.this.id",
                    "}",
                    "",
                ]
            )

        if needs_identity:
            from app_iam import (
                build_app_iam_inventory,
                build_azure_app_iam_hcl,
                extract_workload_roles_from_state,
                write_app_iam_inventory,
            )

            aws_state_path = work / "groups" / raw_group_id / "terraform.tfstate"
            if not aws_state_path.is_file():
                aws_state_path = work / "groups" / group_id / "terraform.tfstate"
            workload_roles: list = []
            if aws_state_path.is_file():
                try:
                    workload_roles = extract_workload_roles_from_state(
                        json.loads(aws_state_path.read_text(encoding="utf-8"))
                    )
                except (OSError, json.JSONDecodeError):
                    workload_roles = []
            write_app_iam_inventory(
                root / "app-iam-inventory.json",
                build_app_iam_inventory(workload_roles, group_id, cloud="azure"),
            )
            main.extend(build_azure_app_iam_hcl(workload_roles, group_id, stable))

        if needs_storage:
            main.extend(
                [
                    'resource "azurerm_storage_account" "primary" {',
                    f'  name                     = "{storage_name}"',
                    "  resource_group_name      = azurerm_resource_group.this.name",
                    "  location                 = azurerm_resource_group.this.location",
                    '  account_tier             = "Standard"',
                    f'  account_replication_type = {hcl_string(sku.get("storage_replication") or "LRS")}',
                    '  min_tls_version          = "TLS1_2"',
                    "  https_traffic_only_enabled = true",
                    "  allow_nested_items_to_be_public = false",
                    "  tags                     = var.tags",
                    "}",
                    "",
                ]
            )

        if needs_function_storage:
            main.extend(
                [
                    'resource "azurerm_storage_account" "function" {',
                    f'  name                     = "{function_storage_name}"',
                    "  resource_group_name      = azurerm_resource_group.this.name",
                    "  location                 = azurerm_resource_group.this.location",
                    '  account_tier             = "Standard"',
                    f'  account_replication_type = {hcl_string(sku.get("storage_replication") or "LRS")}',
                    '  min_tls_version          = "TLS1_2"',
                    "  https_traffic_only_enabled = true",
                    "  allow_nested_items_to_be_public = false",
                    "  tags                     = var.tags",
                    "}",
                    "",
                ]
            )

        if needs_storage_container:
            account_ref = "azurerm_storage_account.primary" if needs_storage else "azurerm_storage_account.function"
            main.extend(
                [
                    'resource "azurerm_storage_container" "primary" {',
                    '  name                  = "data"',
                    f"  storage_account_name  = {account_ref}.name",
                    '  container_access_type = "private"',
                    "}",
                    "",
                ]
            )

        if needs_managed_disk and "storage" in categories:
            main.extend(
                [
                    'resource "azurerm_managed_disk" "data" {',
                    f'  name                 = "disk-{group_id[:50]}"',
                    "  location             = azurerm_resource_group.this.location",
                    "  resource_group_name  = azurerm_resource_group.this.name",
                    '  storage_account_type = "Premium_LRS"',
                    "  create_option        = \"Empty\"",
                    "  disk_size_gb         = 128",
                    "  tags                 = var.tags",
                    "}",
                    "",
                ]
            )

        if "dns" in categories:
            main.extend(
                [
                    'resource "azurerm_dns_zone" "this" {',
                    f'  name                = "example-{stable}.migrated.invalid"',
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  tags                = var.tags",
                    "}",
                    "",
                    "# Sample A record scaffold — confirm record type/TTL/alias targets before apply.",
                    'resource "azurerm_dns_a_record" "primary" {',
                    '  name                = "app"',
                    "  zone_name           = azurerm_dns_zone.this.name",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  ttl                 = 300",
                    '  records             = ["10.0.1.4"]',
                    "  tags                = var.tags",
                    "}",
                    "",
                ]
            )

        if "cache" in categories:
            main.extend(
                [
                    'resource "azurerm_redis_cache" "this" {',
                    f'  name                = "redis-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  capacity            = 0",
                    '  family              = "C"',
                    '  sku_name            = "Basic"',
                    "  minimum_tls_version = \"1.2\"",
                    "  tags                = var.tags",
                    "}",
                    "",
                ]
            )

        if "observability" in categories:
            main.extend(
                [
                    'resource "azurerm_log_analytics_workspace" "this" {',
                    f'  name                = "log-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  sku                 = "PerGB2018"',
                    "  retention_in_days   = 30",
                    "  tags                = var.tags",
                    "}",
                    "",
                ]
            )

        if "containers" in categories:
            if "observability" not in categories:
                main.extend(
                    [
                        'resource "azurerm_log_analytics_workspace" "this" {',
                        f'  name                = "log-{stable}"',
                        "  location            = azurerm_resource_group.this.location",
                        "  resource_group_name = azurerm_resource_group.this.name",
                        '  sku                 = "PerGB2018"',
                        "  retention_in_days   = 30",
                        "  tags                = var.tags",
                        "}",
                        "",
                    ]
                )
            main.extend(
                [
                    'resource "azurerm_container_app_environment" "this" {',
                    f'  name                       = "cae-{stable}"',
                    "  location                   = azurerm_resource_group.this.location",
                    "  resource_group_name        = azurerm_resource_group.this.name",
                    "  log_analytics_workspace_id = azurerm_log_analytics_workspace.this.id",
                    "  tags                       = var.tags",
                    "}",
                    "",
                ]
            )

        if "cdn" in categories:
            main.extend(
                [
                    'resource "azurerm_cdn_frontdoor_profile" "this" {',
                    f'  name                = "afd-{stable}"',
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  sku_name            = "Standard_AzureFrontDoor"',
                    "  tags                = var.tags",
                    "}",
                    "",
                ]
            )

        if "kubernetes" in categories:
            main.extend(
                [
                    'resource "azurerm_kubernetes_cluster" "this" {',
                    f'  name                = "aks-{group_id[:50]}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    f'  dns_prefix          = "aks-{stable}"',
                    "",
                    "  default_node_pool {",
                    '    name       = "system"',
                    "    node_count = 1",
                    f'    vm_size    = {hcl_string(sku.get("aks_node_size") or "Standard_DS2_v2")}',
                    "  }",
                    "",
                    "  identity {",
                    '    type = "SystemAssigned"',
                    "  }",
                    "",
                    "  tags = var.tags",
                    "}",
                    "",
                ]
            )

        if "vmss" in categories:
            main.extend(
                [
                    'resource "azurerm_linux_virtual_machine_scale_set" "this" {',
                    f'  name                            = "vmss-{group_id[:50]}"',
                    "  resource_group_name             = azurerm_resource_group.this.name",
                    "  location                        = azurerm_resource_group.this.location",
                    f'  sku                             = {hcl_string(sku.get("vmss_sku") or "Standard_B2s")}',
                    "  instances                       = 1",
                    "  admin_username                  = var.admin_username",
                    "  disable_password_authentication = true",
                    "  tags                            = var.tags",
                    "",
                    "  admin_ssh_key {",
                    "    username   = var.admin_username",
                    "    public_key = var.admin_ssh_public_key",
                    "  }",
                    "",
                    "  source_image_reference {",
                    '    publisher = "Canonical"',
                    '    offer     = "0001-com-ubuntu-server-jammy"',
                    '    sku       = "22_04-lts"',
                    '    version   = "latest"',
                    "  }",
                    "",
                    "  os_disk {",
                    '    caching              = "ReadWrite"',
                    '    storage_account_type = "Standard_LRS"',
                    "  }",
                    "",
                    "  network_interface {",
                    f'    name    = "nic-vmss-{group_id[:45]}"',
                    "    primary = true",
                    "",
                    "    ip_configuration {",
                    '      name      = "internal"',
                    "      primary   = true",
                    "      subnet_id = azurerm_subnet.default.id",
                    "    }",
                    "  }",
                    "}",
                    "",
                ]
            )

        if "vm" in categories:
            main.extend(
                [
                    'resource "azurerm_network_interface" "vm" {',
                    f'  name                = "nic-{group_id[:55]}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "",
                    "  ip_configuration {",
                    '    name                          = "internal"',
                    "    subnet_id                     = azurerm_subnet.default.id",
                    '    private_ip_address_allocation = "Dynamic"',
                    "  }",
                    "",
                    "  tags = var.tags",
                    "}",
                    "",
                    'resource "azurerm_linux_virtual_machine" "this" {',
                    f'  name                            = "vm-{group_id[:55]}"',
                    "  resource_group_name             = azurerm_resource_group.this.name",
                    "  location                        = azurerm_resource_group.this.location",
                    f'  size                            = {hcl_string(sku.get("vm_size") or "Standard_B2s")}',
                    "  admin_username                  = var.admin_username",
                    "  disable_password_authentication = true",
                    "  network_interface_ids           = [azurerm_network_interface.vm.id]",
                    "  tags                            = var.tags",
                    "",
                    "  admin_ssh_key {",
                    "    username   = var.admin_username",
                    "    public_key = var.admin_ssh_public_key",
                    "  }",
                    "",
                    "  source_image_reference {",
                    '    publisher = "Canonical"',
                    '    offer     = "0001-com-ubuntu-server-jammy"',
                    '    sku       = "22_04-lts"',
                    '    version   = "latest"',
                    "  }",
                    "",
                    "  os_disk {",
                    '    caching              = "ReadWrite"',
                    '    storage_account_type = "Standard_LRS"',
                    "  }",
                    "}",
                    "",
                ]
            )

        if "function" in categories:
            storage_ref = (
                "azurerm_storage_account.primary"
                if needs_storage and not needs_function_storage
                else "azurerm_storage_account.function"
            )
            main.extend(
                [
                    'resource "azurerm_service_plan" "functions" {',
                    f'  name                = "asp-{group_id[:50]}"',
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  location            = azurerm_resource_group.this.location",
                    '  os_type             = "Linux"',
                    '  sku_name            = "Y1"',
                    "  tags                = var.tags",
                    "}",
                    "",
                    'resource "azurerm_linux_function_app" "this" {',
                    f'  name                       = "func-{stable}"',
                    "  resource_group_name        = azurerm_resource_group.this.name",
                    "  location                   = azurerm_resource_group.this.location",
                    "  service_plan_id            = azurerm_service_plan.functions.id",
                    f"  storage_account_name       = {storage_ref}.name",
                    f"  storage_account_access_key = {storage_ref}.primary_access_key",
                    "  https_only                 = true",
                    "  tags                       = var.tags",
                    "",
                    "  site_config {",
                    "    minimum_tls_version = \"1.2\"",
                    "  }",
                    "}",
                    "",
                ]
            )

        if "database_postgres" in categories:
            main.extend(
                [
                    'resource "random_password" "postgres_admin" {',
                    "  length  = 24",
                    "  special = true",
                    "}",
                    "",
                    "# Move administrator_password to Key Vault before production apply (WAF).",
                    'resource "azurerm_postgresql_flexible_server" "this" {',
                    f'  name                   = "psql-{stable}"',
                    "  resource_group_name    = azurerm_resource_group.this.name",
                    "  location               = azurerm_resource_group.this.location",
                    '  version                = "15"',
                    '  administrator_login    = "pgadminuser"',
                    "  administrator_password = random_password.postgres_admin.result",
                    f'  sku_name               = {hcl_string(sku.get("postgres_sku") or "B_Standard_B1ms")}',
                    "  storage_mb             = 32768",
                    "  tags                   = var.tags",
                    "}",
                    "",
                ]
            )

        if "queue" in categories:
            main.extend(
                [
                    'resource "azurerm_servicebus_namespace" "this" {',
                    f'  name                = "sb-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    f'  sku                 = {hcl_string(sku.get("service_bus_sku") or "Standard")}',
                    "  tags                = var.tags",
                    "}",
                    "",
                    'resource "azurerm_servicebus_queue" "this" {',
                    '  name         = "queue-primary"',
                    "  namespace_id = azurerm_servicebus_namespace.this.id",
                    "}",
                    "",
                ]
            )

        if "event" in categories:
            main.extend(
                [
                    'resource "azurerm_eventhub_namespace" "this" {',
                    f'  name                = "evhns-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    f'  sku                 = {hcl_string(sku.get("event_hubs_sku") or "Standard")}',
                    "  capacity            = 1",
                    "  tags                = var.tags",
                    "}",
                    "",
                    'resource "azurerm_eventhub" "this" {',
                    '  name                = "events-primary"',
                    "  namespace_name      = azurerm_eventhub_namespace.this.name",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  partition_count     = 2",
                    "  message_retention   = 1",
                    "}",
                    "",
                ]
            )

        if "load_balancer" in categories:
            if not needs_network:
                main.extend(
                    [
                        'resource "azurerm_virtual_network" "this" {',
                        f'  name                = "vnet-{group_id[:55]}"',
                        "  address_space       = var.vnet_address_space",
                        "  location            = azurerm_resource_group.this.location",
                        "  resource_group_name = azurerm_resource_group.this.name",
                        "  tags                = var.tags",
                        "}",
                        "",
                        'resource "azurerm_subnet" "default" {',
                        '  name                 = "snet-default"',
                        "  resource_group_name  = azurerm_resource_group.this.name",
                        "  virtual_network_name = azurerm_virtual_network.this.name",
                        "  address_prefixes     = var.subnet_address_prefixes",
                        "}",
                        "",
                    ]
                )
            main.extend(
                [
                    'resource "azurerm_public_ip" "lb" {',
                    f'  name                = "pip-lb-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  allocation_method   = "Static"',
                    '  sku                 = "Standard"',
                    "  tags                = var.tags",
                    "}",
                    "",
                    'resource "azurerm_lb" "this" {',
                    f'  name                = "lb-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  sku                 = "Standard"',
                    "  tags                = var.tags",
                    "",
                    "  frontend_ip_configuration {",
                    '    name                 = "frontend"',
                    "    public_ip_address_id = azurerm_public_ip.lb.id",
                    "  }",
                    "}",
                    "",
                    'resource "azurerm_lb_backend_address_pool" "this" {',
                    "  name            = \"backend\"",
                    "  loadbalancer_id = azurerm_lb.this.id",
                    "}",
                    "",
                    'resource "azurerm_lb_probe" "this" {',
                    "  name            = \"tcp-probe\"",
                    "  loadbalancer_id = azurerm_lb.this.id",
                    '  protocol        = "Tcp"',
                    "  port            = 80",
                    "}",
                    "",
                    'resource "azurerm_lb_rule" "this" {',
                    '  name                           = "http"',
                    "  loadbalancer_id                = azurerm_lb.this.id",
                    '  protocol                       = "Tcp"',
                    "  frontend_port                  = 80",
                    "  backend_port                   = 80",
                    '  frontend_ip_configuration_name = "frontend"',
                    "  backend_address_pool_ids       = [azurerm_lb_backend_address_pool.this.id]",
                    "  probe_id                       = azurerm_lb_probe.this.id",
                    "}",
                    "",
                ]
            )

        if "static_ip" in categories and "load_balancer" not in categories:
            main.extend(
                [
                    'resource "azurerm_public_ip" "this" {',
                    f'  name                = "pip-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  allocation_method   = "Static"',
                    '  sku                 = "Standard"',
                    "  tags                = var.tags",
                    "}",
                    "",
                ]
            )

        if "database_nosql" in categories:
            main.extend(
                [
                    'resource "azurerm_cosmosdb_account" "this" {',
                    f'  name                = "cosmos-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  offer_type          = "Standard"',
                    '  kind                = "GlobalDocumentDB"',
                    "  tags                = var.tags",
                    "",
                    "  consistency_policy {",
                    '    consistency_level = "Session"',
                    "  }",
                    "",
                    "  geo_location {",
                    "    location          = azurerm_resource_group.this.location",
                    "    failover_priority = 0",
                    "  }",
                    "}",
                    "",
                    'resource "azurerm_cosmosdb_table" "this" {',
                    '  name                = "primary"',
                    "  resource_group_name = azurerm_resource_group.this.name",
                    "  account_name        = azurerm_cosmosdb_account.this.name",
                    "  throughput          = 400",
                    "}",
                    "",
                ]
            )

        if "api" in categories:
            main.extend(
                [
                    "# Emission=profile_scaffold: APIM review profile for API Gateway equivalents.",
                    'resource "azurerm_api_management" "this" {',
                    f'  name                = "apim-{stable}"',
                    "  location            = azurerm_resource_group.this.location",
                    "  resource_group_name = azurerm_resource_group.this.name",
                    '  publisher_name      = "StackGen Migration Review"',
                    '  publisher_email     = "replace-before-apply@example.invalid"',
                    '  sku_name            = "Developer_1"',
                    "  tags                = var.tags",
                    "}",
                    "",
                ]
            )

        if not (categories & FULL_SCAFFOLD_CATEGORIES) and "identity" not in categories:
            main.append("# No full Azure resource scaffold for this group's categories.")
            main.append("# See mapping-decisions.json emission fields and azure/artifacts/review-needed.md.")
            main.append("")

        decisions_path = root / "mapping-decisions.json"
        decisions_path.write_text(json.dumps(group, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        write_file(root / "main.tf", "\n".join(main))
        azure_resource_counts = _azure_resource_type_counts_in_main(main)
        azure_types = set(azure_resource_counts)
        group_azure_types[group_id] = azure_types
        group_azure_type_counts[group_id] = azure_resource_counts
        write_file(
            root / "outputs.tf",
            """
      output "resource_group_name" {
        value = azurerm_resource_group.this.name
      }

      output "migration_group_id" {
        value = var.tags["migration_group"]
      }
    """,
        )

        rows = [
            "| AWS type | Azure target | Default resource | Status | Emission | Confidence | Review note |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for decision in group["mapping_decisions"]:
            default_target = decision.get("default_target") or "-"
            status = decision.get("status", "mapped")
            emission = decision.get("emission") or "-"
            rows.append(
                f"| `{decision['source_type']}` | {decision['azure_service']} | `{default_target}` | {status} | `{emission}` | `{decision['confidence']}` | {decision['review']} |"
            )
        write_file(
            root / "README.md",
            f"""
      # Azure migration root: {group_id}

      Review-candidate root from `aws/groups/{group_id}/` (CAF naming + WAF security defaults).
      **Not apply-ready** until placeholders and review-needed items are resolved.

      ## Mapping Decisions

      {chr(10).join(rows)}

      ## Validation

      `tofu init -backend=false && tofu fmt -check && tofu validate && tofu plan`
      (live plan needs Reader Azure credentials; never apply from this workflow).
    """,
        )

        mapping_decisions[group_id] = group
        summary_groups.append(
            {
                "group_id": group_id,
                "root": f"azure/groups/{group_id}",
                "categories": sorted(categories),
                "emissions": sorted(emissions),
                "azure_resource_types": sorted(azure_types),
                "confidence": group["confidence"],
                "review_needed": group["review_needed"],
                "review_needed_reason": group.get("review_needed_reason"),
                "review_needed_reasons": group.get("review_needed_reasons") or [],
            }
        )

    write_file(
        azure_root / ".gitignore",
        """
      **/.terraform/
      **/.terraform.lock.hcl
      **/*.tfplan
      **/azure.tfplan
      **/*.out
      **/crash.log
      **/crash.*.log
      **/*.tfstate
      **/*.tfstate.*
      # mktemp leftovers from interrupted validate (final file is validation-report.json)
      artifacts/validation-report.*
      !artifacts/validation-report.json
    """,
    )

    conversion = _compute_infra_conversion(work, group_azure_types, group_decisions_by_id, group_azure_type_counts)

    (artifacts / "mapping-decisions.json").write_text(
        json.dumps(mapping_decisions, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (artifacts / "generation-summary.json").write_text(
        json.dumps(
            {
                "generated_group_count": len(summary_groups),
                "groups": summary_groups,
                "mode": profile.get("mode") or "review_candidate",
                "standards": [
                    "microsoft-caf-naming",
                    "azure-well-architected-security-defaults",
                    "opentofu-hashicorp-root-layout",
                    "honest-emission-labels",
                    "source-instance-coverage-gate-0.90",
                ],
                "emission_counts": emission_counts,
                "mapping_catalog": profile.get("mapping_catalog", {}),
                **{
                    k: conversion[k]
                    for k in (
                        "infra_eligible_count",
                        "infra_converted_count",
                        "infra_conversion_rate",
                        "infra_conversion_ok",
                        "identity_scaffold_count",
                        "app_iam_eligible_count",
                        "app_iam_converted_count",
                        "app_iam_conversion_rate",
                        "app_iam_conversion_ok",
                        "infra_conversion_gaps",
                        "source_coverage_applicable_count",
                        "source_coverage_converted_count",
                        "source_coverage_rate",
                        "source_coverage_threshold",
                        "source_coverage_ok",
                        "source_non_applicable_count",
                        "source_unsupported_count",
                        "source_instance_count",
                        "app_iam_conversion_threshold",
                    )
                },
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    write_file(
        azure_root / "README.md",
        f"""
  # Azure destination IaC (review candidate)

  Generated by StackGen `aws-migrator` after AWS reverse-IaC validation.

  ## Standards

  - Microsoft CAF-style names (`rg-`, `vnet-`, `snet-`, `nsg-`, `st`, `id-`, ...)
  - Azure Well-Architected defaults: TLS 1.2+, HTTPS-only storage, private containers, SSH-only VMs
  - OpenTofu/HashiCorp root layout per group; runtime logs/plans gitignored
  - Catalog `emission` field tells you what was actually generated vs documented

  ## Layout

  - `groups/<group_id>/` — Terraform roots
  - `artifacts/` — blueprint, mapping decisions, validation report, review-needed
  - `.gitignore` — excludes `*.out`, `.terraform`, plans, state

  This workflow never applies Azure resources.
""",
    )

    return {
        "generated_group_count": len(summary_groups),
        "emission_counts": emission_counts,
        **{
            k: conversion[k]
            for k in (
                "infra_conversion_rate",
                "infra_conversion_ok",
                "source_coverage_applicable_count",
                "source_coverage_converted_count",
                "source_coverage_rate",
                "source_coverage_threshold",
                "source_coverage_ok",
                "source_non_applicable_count",
                "source_unsupported_count",
                "source_instance_count",
                "app_iam_conversion_threshold",
                "app_iam_conversion_rate",
                "app_iam_conversion_ok",
                "identity_scaffold_count",
                "app_iam_eligible_count",
                "app_iam_converted_count",
            )
        },
    }


def main(argv=None):
    argv = argv or sys.argv[1:]
    work = Path(argv[0] if argv else ".")
    result = generate(work)
    print(f"azure_iac_group_count={result['generated_group_count']}")
    print(f"azure_emission_counts={json.dumps(result['emission_counts'], sort_keys=True)}")
    print(f"azure_infra_conversion_rate={result.get('infra_conversion_rate', 0)}")
    print(f"azure_infra_conversion_ok={str(result.get('infra_conversion_ok', False)).lower()}")
    print(f"azure_source_coverage_rate={result.get('source_coverage_rate', 0)}")
    print(f"azure_source_coverage_ok={str(result.get('source_coverage_ok', False)).lower()}")
    print(f"azure_identity_scaffold_count={result.get('identity_scaffold_count', 0)}")
    print(f"azure_app_iam_eligible_count={result.get('app_iam_eligible_count', 0)}")
    print(f"azure_app_iam_converted_count={result.get('app_iam_converted_count', 0)}")
    print(f"azure_app_iam_conversion_rate={result.get('app_iam_conversion_rate', 0)}")
    print(f"azure_app_iam_conversion_ok={str(result.get('app_iam_conversion_ok', False)).lower()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
