#!/usr/bin/env python3
"""Generate review-candidate GCP Terraform roots from the migration blueprint.

Standards this emitter aims for (realistic, not perfect fidelity):
- Google Cloud naming conventions (vpc-, subnet-, gcs-, sa-, gke-, ...)
- Baseline security defaults: uniform bucket-level access, private-by-default where applicable,
  OS Login / SSH keys only (no password defaults in git)
- HashiCorp/OpenTofu root layout: versions/providers/variables/outputs + .gitignore
- Honest emission labels from gcp_mapping_catalog (mapped ≠ full equivalent)

This is review-candidate IaC: safe to open a PR and inspect. It is not apply-ready
landing-zone / Fabric / full IAM composition for every AWS service.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
import textwrap
from pathlib import Path

# Script-pack helpers (app_iam.py) live beside this file under $WORK_ROOT/scripts.
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

PLACEHOLDER_SSH_PUBKEY = (
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDu+F2KA+8AwzD9H8iJXO37rAD35pgzahB5DLNFWicc9 "
    "REPLACE-BEFORE-APPLY@stackgen-aws-migrator"
)

# Nile tagging-labeling-standard §7 required GCP labels (TAG-002). Values must not
# be placeholders rejected by TAG-003 (tbd/test/unknown/placeholder/changeme/none).
# Session c6cb3339: emit these at generate time so governance-conform can pass without
# an LLM rewrite of every group's variables.tf.
REQUIRED_GCP_LABELS = {
    "owner": "platformengineering",
    "created_by": "stackgen-aws-migrator",
    "cost_center": "cc-migration",
    "environment": "dev",
    "function": "migration",
    "service": "nile",
    "repo": "walmart-stackgen-nile-factory",
    "application_name": "projectnile",
    "notification_distlist": "nile-ops",
    "ssp": "ssp-migration",
    "tr_product_id": "tr-migration",
    "apm_id": "apm-migration",
}

STANDARDS_HEADER = """# Review-candidate GCP root generated by StackGen aws-migrator (GCP destination).
# Standards: Google Cloud naming, private-by-default storage, OS Login / SSH-only compute,
# OpenTofu/HashiCorp root layout. Not full landing-zone / Fabric modules.
# Do not apply until operators replace placeholders and complete review-needed items.
"""

FULL_SCAFFOLD_CATEGORIES = {
    "network",
    "kubernetes",
    "vmss",
    "vm",
    "function",
    "storage",
    "database_postgres",
    "database_nosql",
    "queue",
    "event",
    "dns",
    "cache",
    "observability",
    "containers",
    "cdn",
    "static_ip",
    "load_balancer",
}

# Conversion targets are source-instance weighted, not group-count weighted.
SOURCE_COVERAGE_THRESHOLD = 0.90
INFRA_CATEGORIES = FULL_SCAFFOLD_CATEGORIES | {"api", "key_management", "analytics", "cdn"}

# google_* resource name prefixes that satisfy conversion for a category.
CATEGORY_GOOGLE_MARKERS = {
    "network": (
        "google_compute_network",
        "google_compute_subnetwork",
        "google_compute_firewall",
        "google_compute_route",
        "google_compute_router",
    ),
    "static_ip": ("google_compute_address",),
    "load_balancer": (
        "google_compute_forwarding_rule",
        "google_compute_backend_service",
        "google_compute_region_backend_service",
        "google_compute_health_check",
        "google_compute_region_health_check",
        "google_compute_address",
    ),
    "dns": ("google_dns_",),
    "observability": ("google_logging_",),
    "queue": ("google_pubsub_",),
    "event": ("google_pubsub_",),
    "vm": ("google_compute_instance",),
    "vmss": ("google_compute_instance_template", "google_compute_region_instance_group_manager"),
    "storage": ("google_storage_bucket",),
    "function": ("google_cloudfunctions", "google_storage_bucket"),
    "database_postgres": ("google_sql_",),
    "database_nosql": ("google_bigtable_", "google_firestore_"),
    "cache": ("google_redis_",),
    "kubernetes": ("google_container_",),
    "containers": ("google_cloud_run_",),
    "cdn": ("google_compute_global_address",),
    "api": ("google_api_gateway_", "google_cloud_run_"),
    "key_management": ("google_kms_",),
    "analytics": ("google_bigquery_",),
    # Acquisition app-IAM: SA alone is not enough — custom role must land too.
    "identity": ("google_service_account",),
}


def safe_name(value, max_len=48):
    value = re.sub(r"[^a-z0-9-]+", "-", (value or "group").lower()).strip("-")
    return (value[:max_len].strip("-") or "group")


def hcl_string(value):
    return json.dumps(str(value))


def gcp_instance_template_name_prefix(group_id: str) -> str:
    """google_compute_instance_template.name_prefix must be ≤37 (final name ≤63)."""
    return f"mig-{group_id}"[:36] + "-"


def hcl_string_map(mapping: dict) -> str:
    """Render a map(string) default without breaking textwrap.dedent on parent templates.

    Multi-line maps with a bare `{` line destroy the common leading whitespace
    prefix that textwrap.dedent relies on, so empty-group variables.tf failed
    `tofu fmt`. A single-line object keeps the parent template's indent intact;
    `tofu fmt` can expand it later during validate.
    """
    if not mapping:
        return "{}"
    inner = ", ".join(
        f"{hcl_string(key)} = {hcl_string(value)}" for key, value in sorted(mapping.items())
    )
    return "{ " + inner + " }"


def write_file(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).lstrip() + "\n", encoding="utf-8")


def _google_resource_type_counts_in_main(main_lines: list[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for line in main_lines:
        m = re.search(r'resource\s+"(google_[^"]+)"\s+"', line)
        if m:
            counts[m.group(1)] = counts.get(m.group(1), 0) + 1
    return counts


def _google_resource_types_in_main(main_lines: list[str]) -> set[str]:
    return set(_google_resource_type_counts_in_main(main_lines))



def _consume_mapped_target_instance(remaining: dict[str, int], decision: dict) -> str | None:
    """Consume one actually-emitted target resource assigned by the catalog."""
    candidates = []
    default_target = decision.get("default_target")
    targets = [default_target] if default_target else []
    for target in targets:
        if isinstance(target, str) and target.startswith("google_") and target not in candidates:
            candidates.append(target)
    for target in candidates:
        if remaining.get(target, 0) > 0:
            remaining[target] -= 1
            return target
    return None

def _source_cloudwatch_log_groups(work: Path, raw_group_id: str, group_id: str) -> list[dict]:
    """Read managed CloudWatch log-group instances and their source settings."""
    candidates = [work / "groups" / raw_group_id / "terraform.tfstate"]
    normalized = work / "groups" / group_id / "terraform.tfstate"
    if normalized not in candidates:
        candidates.append(normalized)
    state_path = next((path for path in candidates if path.is_file()), None)
    if state_path is None:
        return []
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    instances = []
    for resource in state.get("resources") or []:
        if resource.get("mode") != "managed" or resource.get("type") != "aws_cloudwatch_log_group":
            continue
        for instance in resource.get("instances") or []:
            attrs = instance.get("attributes") or {}
            instances.append({
                "name": str(attrs.get("name") or "").strip(),
                "retention_in_days": attrs.get("retention_in_days"),
            })
    return instances


def _cloud_logging_bucket_id(source_name: str, stable: str, index: int, used: set[str]) -> str:
    stem = safe_name(source_name, max_len=75) if source_name else f"log-{stable}-{index}"
    bucket_id = f"migration-{stem}"[:100].rstrip("-")
    if bucket_id in used:
        suffix = hashlib.sha256(f"{source_name}:{index}".encode()).hexdigest()[:8]
        bucket_id = f"{bucket_id[:91]}-{suffix}"
    used.add(bucket_id)
    return bucket_id


def _emit_cloud_logging_buckets(
    main: list[str], work: Path, raw_group_id: str, group_id: str, stable: str
) -> dict:
    """Emit one Cloud Logging bucket per source log group; never collapse silently."""
    source_groups = _source_cloudwatch_log_groups(work, raw_group_id, group_id)
    if not source_groups:
        main.extend([
            "# No AWS CloudWatch log-group state found: explicit placeholder, not a source-complete mapping.",
            'resource "google_logging_project_bucket_config" "this" {',
            "  project        = var.project_id",
            '  location       = "global"',
            f'  bucket_id      = "migration-{stable}"',
            "  retention_days = 30 # Assumption: confirm policy and source retention before apply.",
            "}",
            "",
        ])
        return {
            "source_count": 0,
            "emitted_count": 1,
            "assumption_count": 1,
            "source_inventory_available": False,
            "routing_status": "unwired_no_source_inventory",
            "mappings": [],
        }

    used: set[str] = set()
    assumptions = 0
    mappings = []
    for index, source in enumerate(source_groups, start=1):
        raw_retention = source.get("retention_in_days")
        retention_assumption = False
        try:
            retention = int(raw_retention)
        except (TypeError, ValueError):
            retention = 0
            retention_assumption = True
        if retention <= 0 or retention > 3650:
            retention_assumption = True
            # Provider v5.40 defaults zero to 30 days. AWS 0 means never expire.
            # Preserve no false equivalence: document this as a required decision.
            retention = 30
            assumptions += 1
        bucket_id = _cloud_logging_bucket_id(source["name"], stable, index, used)
        resource_name = f"source_{index}"
        if retention_assumption:
            main.append("# TODO(apply-readiness): source retention is unset/never-expire; confirm the 30-day destination assumption.")
        main.extend([
            f"# Source log group: {json.dumps(source['name'] or '<missing>')}; source retention={raw_retention!r}.",
            "# TODO(apply-readiness): Cloud Logging bucket created; CloudWatch-to-GCP log routing/sink permissions are not configured here.",
            f'resource "google_logging_project_bucket_config" "{resource_name}" {{',
            "  project        = var.project_id",
            '  location       = "global"',
            f"  bucket_id      = {hcl_string(bucket_id)}",
            f"  retention_days = {retention}",
            "}",
            "",
        ])
        mappings.append({
            "source_name": source["name"],
            "source_retention_in_days": raw_retention,
            "target_address": f"google_logging_project_bucket_config.{resource_name}",
            "target_bucket_id": bucket_id,
            "target_retention_days": retention,
            "retention_assumption": retention_assumption,
            "routing_status": "bucket_created_not_routed",
            "note": "Creating a logging bucket does not route CloudWatch log entries; author/verify sinks or agents and destination permissions before claiming observability migration.",
        })
    return {
        "source_count": len(source_groups),
        "emitted_count": len(source_groups),
        "assumption_count": assumptions,
        "source_inventory_available": True,
        "routing_status": "bucket_created_routing_not_configured",
        "mappings": mappings,
    }


def _coverage_rate(converted: int, applicable: int) -> float | None:
    """Return source-instance coverage; non-applicable rows stay outside the denominator."""
    return round(converted / applicable, 4) if applicable else None


def _coverage_ok(converted: int, applicable: int) -> bool:
    rate = _coverage_rate(converted, applicable)
    return rate is not None and rate >= SOURCE_COVERAGE_THRESHOLD


def _category_satisfied(category: str, google_types: set[str]) -> bool:
    markers = CATEGORY_GOOGLE_MARKERS.get(category) or ()
    if not markers:
        # Unknown infra category: any non-SA google_* counts as progress.
        return any(t != "google_service_account" for t in google_types)
    for marker in markers:
        for gtype in google_types:
            if gtype == marker or gtype.startswith(marker):
                return True
    return False


def _count_aws_instances(work: Path) -> dict[str, dict[str, int]]:
    """Count managed AWS instances in each source shard; invalid states fail closed."""
    out: dict[str, dict[str, int]] = {}
    groups_dir = work / "groups"
    if not groups_dir.is_dir():
        return out
    for state_path in sorted(groups_dir.glob("*/terraform.tfstate")):
        try:
            state = json.loads(state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"cannot read AWS source state {state_path}: {exc}") from exc
        counts: dict[str, int] = {}
        for resource in state.get("resources") or []:
            if resource.get("mode") != "managed":
                continue
            rtype = str(resource.get("type") or "")
            if rtype.startswith("aws_"):
                counts[rtype] = counts.get(rtype, 0) + len(resource.get("instances") or [1])
        out[state_path.parent.name] = counts
    return out


def _validate_source_reconciliation(work: Path, blueprint: dict) -> dict:
    """Ensure every handed-off AWS shard and source instance reaches the blueprint."""
    states = _count_aws_instances(work)
    if not states:
        raise ValueError("no AWS source terraform.tfstate files found under groups/")
    source_ids = set(states)
    groups = blueprint.get("groups") or []
    blueprint_ids = [str(g.get("group_id") or "") for g in groups]
    if any(not gid for gid in blueprint_ids) or len(set(blueprint_ids)) != len(blueprint_ids):
        raise ValueError("GCP migration blueprint has missing or duplicate group IDs")
    if source_ids != set(blueprint_ids):
        raise ValueError(
            "GCP blueprint does not cover the complete AWS source group set: "
            f"source groups={len(source_ids)}, blueprint groups={len(blueprint_ids)}, "
            f"missing blueprint groups={sorted(source_ids-set(blueprint_ids))[:20]}, "
            f"unexpected blueprint groups={sorted(set(blueprint_ids)-source_ids)[:20]}"
        )
    state_counts = {gid: sum(types.values()) for gid, types in states.items()}
    blueprint_counts = {str(g["group_id"]): int(g.get("source_resource_count") or 0) for g in groups}
    mismatches = {gid: {"state": state_counts[gid], "blueprint": blueprint_counts[gid]}
                  for gid in source_ids if state_counts[gid] != blueprint_counts[gid]}
    if mismatches:
        raise ValueError(f"GCP blueprint resource counts differ from source states: {dict(list(mismatches.items())[:20])}")
    source_total = sum(state_counts.values())
    return {
        "source_group_count": len(source_ids),
        "blueprint_group_count": len(blueprint_ids),
        "source_resource_count": source_total,
        "blueprint_resource_count": sum(blueprint_counts.values()),
        "source_resource_counts_by_type": {
            t: sum(group.get(t, 0) for group in states.values())
            for t in sorted({t for group in states.values() for t in group})
        },
        "group_resource_counts": dict(sorted(state_counts.items())),
        "group_reconciliation_ok": True,
        "resource_reconciliation_ok": source_total == sum(blueprint_counts.values()),
    }


def _compute_infra_conversion(
    work: Path,
    group_google_types: dict[str, set[str]],
    group_decisions: dict[str, list],
    group_google_type_counts: dict[str, dict[str, int]] | None = None,
) -> dict:
    """Instance-weighted infra + app-IAM conversion metrics.

    Infra conversion excludes identity (reported separately as app_iam_*).
    App IAM conversion counts workload aws_iam_role / policy / role_policy instances
    that received SA + custom_role scaffolds — the acquisition permission surface.
    """
    try:
        from gcp_mapping_catalog import load_catalog, resolve
    except ImportError:
        sys.path.insert(0, str((work / "scripts").resolve()))
        from gcp_mapping_catalog import load_catalog, resolve  # type: ignore

    catalog_path = work / "scripts" / "mappings" / "aws-to-gcp.json"
    if not catalog_path.is_file():
        catalog_path = Path(__file__).resolve().parent.parent / "mappings" / "aws-to-gcp.json"
    catalog = load_catalog(catalog_path)

    aws_by_group = _count_aws_instances(work)
    eligible = 0
    converted = 0
    identity_instances = 0
    app_iam_eligible = 0
    app_iam_converted = 0
    applicable = 0
    applicable_converted = 0
    non_applicable_instances = 0
    unsupported_instances = 0
    gaps: list[dict] = []
    gap_keys: set[tuple[str, str]] = set()
    app_iam_types = {"aws_iam_role", "aws_iam_policy", "aws_iam_role_policy"}

    def _append_gap(raw_group_id: str, source_type: str, count: int, category: str, reason: str, **extra) -> None:
        # Normalize so hyphen/underscore aliases of the same shard do not double-count.
        gid = safe_name(raw_group_id)
        key = (gid, source_type)
        if key in gap_keys:
            return
        gap_keys.add(key)
        row = {
            "group_id": gid,
            "source_type": source_type,
            "count": count,
            "category": category,
            "reason": reason,
        }
        row.update(extra)
        gaps.append(row)

    group_ids = set(aws_by_group) | set(group_decisions)
    for group_id in sorted(group_ids):
        gid = safe_name(group_id)
        remaining = dict((group_google_type_counts or {}).get(gid, {}))
        decisions_by_type = {
            d.get("source_type"): d for d in (group_decisions.get(group_id) or []) if d.get("source_type")
        }
        type_counts = aws_by_group.get(group_id) or {src: 1 for src in decisions_by_type}
        for source_type, count in sorted(type_counts.items()):
            decision = decisions_by_type.get(source_type) or resolve(catalog, source_type)
            status = decision.get("status") or "unsupported"
            category = decision.get("category") or "placeholder"
            if status == "non_applicable" or category == "non_applicable":
                non_applicable_instances += count
                continue

            applicable += count
            eligible += count
            identity_source = source_type in app_iam_types or category == "identity"
            if identity_source:
                identity_instances += count
                app_iam_eligible += count
            target = decision.get("default_target")
            if source_type == "aws_iam_role":
                target = "google_service_account"
            elif source_type in {"aws_iam_policy", "aws_iam_role_policy"}:
                target = "google_project_iam_custom_role"

            covered = 0
            if status == "mapped" and isinstance(target, str) and target.startswith("google_"):
                covered = min(count, remaining.get(target, 0))
                remaining[target] = remaining.get(target, 0) - covered
            converted += covered
            applicable_converted += covered
            if identity_source:
                app_iam_converted += covered
            if covered < count:
                if status != "mapped" or not isinstance(target, str):
                    unsupported_instances += count - covered
                reason = "unmapped_source_type" if status != "mapped" else "target_resource_instance_missing"
                _append_gap(group_id, source_type, count - covered, category, reason,
                            target_resource_type=target, emission=decision.get("emission"), status=status)

    rate = round(converted / eligible, 4) if eligible else 0.0
    app_rate = round(app_iam_converted / app_iam_eligible, 4) if app_iam_eligible else None
    source_coverage_rate = _coverage_rate(applicable_converted, applicable)
    source_coverage_ok = _coverage_ok(applicable_converted, applicable)
    return {
        "infra_eligible_count": eligible,
        "infra_converted_count": converted,
        "infra_conversion_rate": rate,
        "infra_conversion_ok": eligible > 0 and rate >= SOURCE_COVERAGE_THRESHOLD,
        "source_coverage_applicable_count": applicable,
        "source_coverage_converted_count": applicable_converted,
        "source_coverage_rate": source_coverage_rate,
        "source_coverage_threshold": SOURCE_COVERAGE_THRESHOLD,
        "source_coverage_ok": source_coverage_ok,
        "source_non_applicable_count": non_applicable_instances,
        "source_unsupported_count": unsupported_instances,
        "source_instance_count": applicable + non_applicable_instances,
        "identity_scaffold_count": identity_instances,
        "app_iam_eligible_count": app_iam_eligible,
        "app_iam_converted_count": app_iam_converted,
        "app_iam_conversion_rate": app_rate,
        "app_iam_conversion_threshold": SOURCE_COVERAGE_THRESHOLD,
        "app_iam_conversion_ok": app_iam_eligible > 0 and app_rate is not None and app_rate >= SOURCE_COVERAGE_THRESHOLD,
        "infra_conversion_gaps": gaps[:50],
    }


def generate(work: Path) -> dict:
    gcp_root = work / "gcp"
    groups_root = gcp_root / "groups"
    artifacts = gcp_root / "artifacts"
    blueprint = json.loads((artifacts / "migration-blueprint.json").read_text(encoding="utf-8"))
    reconciliation = _validate_source_reconciliation(work, blueprint)
    profile = blueprint["profile"]
    defaults = profile.get("defaults") or {}
    networking = defaults.get("networking") or {}
    subnet_cidr = networking.get("subnet_cidr") or "10.0.1.0/24"
    sku = defaults.get("sku") or {}
    project_id = defaults.get("project_id") or "REPLACE-GCP-PROJECT"
    region = defaults.get("region") or defaults.get("location") or "us-central1"

    if groups_root.exists():
        shutil.rmtree(groups_root)
    groups_root.mkdir(parents=True, exist_ok=True)

    mapping_decisions = {}
    summary_groups = []
    emission_counts = {}
    group_google_types: dict[str, set[str]] = {}
    group_google_type_counts: dict[str, dict[str, int]] = {}
    group_decisions_by_id: dict[str, list] = {}

    for group in blueprint["groups"]:
        group_id = safe_name(group["group_id"])
        raw_group_id = group["group_id"]
        stable = group["stable_hash"]
        categories = set(group.get("target_categories") or [])
        decisions = group.get("mapping_decisions") or []
        group_decisions_by_id[raw_group_id] = decisions
        group_decisions_by_id[group_id] = decisions
        emissions = set()
        for decision in decisions:
            emissions.add(decision.get("emission") or "resource_group_only")
        for em in emissions:
            emission_counts[em] = emission_counts.get(em, 0) + 1

        root = groups_root / group_id
        root.mkdir(parents=True, exist_ok=True)

        needs_network = bool(
            categories
            & {
                "network",
                "kubernetes",
                "vmss",
                "vm",
                "function",
                "database_postgres",
                "database_nosql",
                "load_balancer",
                "containers",
                "cache",
            }
        )
        needs_identity = bool(categories & {"identity", "kubernetes", "vmss", "vm", "function", "database_postgres", "containers"})
        needs_storage = bool(categories & {"storage", "function"})

        write_file(
            root / "versions.tf",
            """
      terraform {
        required_version = ">= 1.6.0"

        required_providers {
          google = {
            source  = "hashicorp/google"
            version = "~> 5.40"
          }
          random = {
            source  = "hashicorp/random"
            version = "~> 3.6"
          }
        }
      }
    """,
        )

        write_file(
            root / "providers.tf",
            """
      provider "google" {
        project = var.project_id
        region  = var.region
        # Applied to every resource that supports labels (network/firewall/SA do not).
        default_labels = var.labels
      }
    """,
        )

        label_name = re.sub(r"[^a-z0-9_-]", "-", group_id.lower())[:63] or "migration-group"
        labels = {
            **(defaults.get("tags") or defaults.get("labels") or {}),
            **REQUIRED_GCP_LABELS,
            "name": label_name,
            "migration_group": group_id,
            "generated_by": "stackgen-aws-migrator",
            "migration_mode": "aws-to-gcp",
            "standards": "gcp-review-candidate",
        }
        # GCP labels must be lowercase; sanitize keys/values lightly for HCL defaults.
        labels = {re.sub(r"[^a-z0-9_-]", "-", k.lower())[:63]: re.sub(r"[^a-z0-9_-]", "-", str(v).lower())[:63] for k, v in labels.items()}
        labels_hcl = hcl_string_map(labels)
        write_file(
            root / "variables.tf",
            f"""
      variable "project_id" {{
        description = "GCP project ID that will own these resources."
        type        = string
        default     = {hcl_string(project_id)}
      }}

      variable "region" {{
        description = "Primary GCP region."
        type        = string
        default     = {hcl_string(region)}
      }}

      variable "labels" {{
        description = "Resource labels including Nile required keys (owner, cost_center, …)."
        type        = map(string)
        default     = {labels_hcl}
      }}

      variable "subnet_cidr" {{
        description = "Default subnet CIDR. Replace with enterprise IPAM allocations before apply."
        type        = string
        default     = {hcl_string(subnet_cidr)}
      }}

      variable "admin_ssh_public_key" {{
        description = "SSH public key. Placeholder is public-only and MUST be replaced before apply."
        type        = string
        default     = {hcl_string(PLACEHOLDER_SSH_PUBKEY)}
      }}
    """,
        )

        main = [STANDARDS_HEADER.rstrip(), ""]
        main.append("# Project-scoped scaffold: resources land in var.project_id (no Azure-style resource group).")
        main.append("")

        if needs_network:
            main.extend(
                [
                    'resource "google_compute_network" "this" {',
                    f'  name                    = "vpc-{group_id[:55]}"',
                    "  auto_create_subnetworks = false",
                    "}",
                    "",
                    'resource "google_compute_subnetwork" "default" {',
                    '  name          = "subnet-default"',
                    "  ip_cidr_range = var.subnet_cidr",
                    "  region        = var.region",
                    "  network       = google_compute_network.this.id",
                    "  private_ip_google_access = true",
                    "}",
                    "",
                    # VPC firewall/network/subnet have no labels attr in google provider
                    # (PRIO-001 residuals soft-gated; see governance-exceptions).
                    'resource "google_compute_firewall" "deny_ingress" {',
                    f'  name    = "fw-deny-ingress-{stable}"',
                    "  network = google_compute_network.this.name",
                    "",
                    '  direction = "INGRESS"',
                    "  priority  = 65534",
                    '  deny {',
                    '    protocol = "all"',
                    "  }",
                    '  source_ranges = ["0.0.0.0/0"]',
                    '  description   = "Baseline deny-all ingress; open explicitly after review."',
                    "}",
                    "",
                ]
            )

        if needs_identity:
            from app_iam import (
                build_app_iam_inventory,
                build_gcp_app_iam_hcl,
                extract_workload_roles_from_state,
                write_app_iam_inventory,
            )

            aws_state_path = work / "groups" / raw_group_id / "terraform.tfstate"
            if not aws_state_path.is_file():
                aws_state_path = work / "groups" / group_id / "terraform.tfstate"
            workload_roles: list = []
            if aws_state_path.is_file():
                try:
                    workload_roles = extract_workload_roles_from_state(
                        json.loads(aws_state_path.read_text(encoding="utf-8"))
                    )
                except (OSError, json.JSONDecodeError):
                    workload_roles = []
            write_app_iam_inventory(
                root / "app-iam-inventory.json",
                build_app_iam_inventory(workload_roles, group_id, cloud="gcp"),
            )
            main.extend(build_gcp_app_iam_hcl(workload_roles, group_id, stable))

        if needs_storage:
            main.extend(
                [
                    'resource "google_storage_bucket" "primary" {',
                    f'  name                        = "gcs-{stable}"',
                    "  location                    = var.region",
                    "  uniform_bucket_level_access = true",
                    "  public_access_prevention    = \"enforced\"",
                    "  force_destroy               = false",
                    "  labels                      = var.labels",
                    "",
                    "  versioning {",
                    "    enabled = true",
                    "  }",
                    "}",
                    "",
                ]
            )

        if "dns" in categories:
            main.extend(
                [
                    'resource "google_dns_managed_zone" "this" {',
                    f'  name        = "dns-{stable}"',
                    f'  dns_name    = "example-{stable}.migrated.invalid."',
                    "  description = \"Review-candidate DNS zone from AWS Route53 mapping\"",
                    "  labels      = var.labels",
                    "}",
                    "",
                    "# Sample record scaffold — replace type/rrdatas with Route53 record values before apply.",
                    'resource "google_dns_record_set" "primary" {',
                    '  name         = "app.${google_dns_managed_zone.this.dns_name}"',
                    "  managed_zone = google_dns_managed_zone.this.name",
                    '  type         = "A"',
                    "  ttl          = 300",
                    '  rrdatas      = ["203.0.113.10"]',
                    "}",
                    "",
                ]
            )

        if "cache" in categories:
            main.extend(
                [
                    'resource "google_redis_instance" "this" {',
                    f'  name               = "redis-{stable}"',
                    '  tier               = "BASIC"',
                    "  memory_size_gb     = 1",
                    "  region             = var.region",
                    '  redis_version      = "REDIS_7_0"',
                    "  authorized_network = google_compute_network.this.id",
                    "  labels             = var.labels",
                    "}",
                    "",
                ]
            )

        logging_emission = {}
        if "observability" in categories:
            logging_emission = _emit_cloud_logging_buckets(
                main, work, raw_group_id, group_id, stable
            )

        if "containers" in categories:
            main.extend(
                [
                    'resource "google_cloud_run_v2_service" "this" {',
                    f'  name     = "run-{stable}"',
                    "  location = var.region",
                    "  labels   = var.labels",
                    "",
                    "  template {",
                    "    containers {",
                    '      image = "us-docker.pkg.dev/cloudrun/container/hello"',
                    "    }",
                    "  }",
                    "",
                    "  ingress = \"INGRESS_TRAFFIC_INTERNAL_ONLY\"",
                    "}",
                    "",
                ]
            )

        # API Gateway maps to google_api_gateway_* (often google-beta). Emit a Cloud Run
        # front-door scaffold so category=api is satisfied without a beta provider pin;
        # OpenAPI/API Gateway config remains a human review follow-up.
        if "api" in categories and not any("google_cloud_run" in line for line in main):
            main.extend(
                [
                    "# Emission=profile_scaffold: AWS API Gateway → Cloud Run front door;",
                    "# replace with google_api_gateway_api (+ OpenAPI) before production apply.",
                    'resource "google_cloud_run_v2_service" "api" {',
                    f'  name     = "api-{stable}"',
                    "  location = var.region",
                    "  labels   = var.labels",
                    "",
                    "  template {",
                    "    containers {",
                    '      image = "us-docker.pkg.dev/cloudrun/container/hello"',
                    "    }",
                    "  }",
                    "",
                    '  ingress = "INGRESS_TRAFFIC_ALL"',
                    "}",
                    "",
                ]
            )

        if "cdn" in categories:
            main.extend(
                [
                    "# Emission=profile_scaffold: global forwarding rule placeholder — deep CDN/LB follow-up required.",
                    'resource "google_compute_global_address" "cdn" {',
                    f'  name   = "glb-{stable}"',
                    "  labels = var.labels",
                    "}",
                    "",
                ]
            )

        if "kubernetes" in categories:
            main.extend(
                [
                    'resource "google_container_cluster" "this" {',
                    f'  name     = "gke-{group_id[:50]}"',
                    "  location = var.region",
                    "",
                    "  remove_default_node_pool = true",
                    "  initial_node_count       = 1",
                    "",
                    "  network    = google_compute_network.this.name",
                    "  subnetwork = google_compute_subnetwork.default.name",
                    "",
                    "  release_channel {",
                    '    channel = "REGULAR"',
                    "  }",
                    "",
                    "  workload_identity_config {",
                    "    workload_pool = \"${var.project_id}.svc.id.goog\"",
                    "  }",
                    "",
                    "  resource_labels = var.labels",
                    "}",
                    "",
                    'resource "google_container_node_pool" "system" {',
                    f'  name       = "system"',
                    "  location   = var.region",
                    "  cluster    = google_container_cluster.this.name",
                    "  node_count = 1",
                    "",
                    "  node_config {",
                    f'    machine_type = {hcl_string(sku.get("gke_node_size") or "e2-medium")}',
                    "    labels       = var.labels",
                    "    oauth_scopes = [",
                    '      "https://www.googleapis.com/auth/cloud-platform",',
                    "    ]",
                    "  }",
                    "}",
                    "",
                ]
            )

        if "vmss" in categories:
            # google_compute_instance_template.name_prefix max 37 (final name ≤63).
            mig_name_prefix = gcp_instance_template_name_prefix(group_id)
            main.extend(
                [
                    'resource "google_compute_instance_template" "this" {',
                    f"  name_prefix  = {hcl_string(mig_name_prefix)}",
                    f'  machine_type = {hcl_string(sku.get("mig_machine_type") or "e2-medium")}',
                    "",
                    "  disk {",
                    '    source_image = "projects/debian-cloud/global/images/family/debian-12"',
                    "    auto_delete  = true",
                    "    boot         = true",
                    "  }",
                    "",
                    "  network_interface {",
                    "    network    = google_compute_network.this.name",
                    "    subnetwork = google_compute_subnetwork.default.name",
                    "  }",
                    "",
                    "  metadata = {",
                    '    enable-oslogin = "TRUE"',
                    "    ssh-keys       = \"ubuntu:${var.admin_ssh_public_key}\"",
                    "  }",
                    "",
                    "  labels = var.labels",
                    "",
                    "  lifecycle {",
                    "    create_before_destroy = true",
                    "  }",
                    "}",
                    "",
                ]
            )

        if "vm" in categories:
            main.extend(
                [
                    'resource "google_compute_instance" "this" {',
                    f'  name         = "vm-{group_id[:55]}"',
                    f'  machine_type = {hcl_string(sku.get("vm_machine_type") or "e2-medium")}',
                    "  zone         = \"${var.region}-a\"",
                    "  labels       = var.labels",
                    "",
                    "  boot_disk {",
                    "    initialize_params {",
                    '      image = "debian-cloud/debian-12"',
                    "    }",
                    "  }",
                    "",
                    "  network_interface {",
                    "    network    = google_compute_network.this.name",
                    "    subnetwork = google_compute_subnetwork.default.name",
                    "  }",
                    "",
                    "  metadata = {",
                    '    enable-oslogin = "TRUE"',
                    "    ssh-keys       = \"ubuntu:${var.admin_ssh_public_key}\"",
                    "  }",
                    "}",
                    "",
                ]
            )

        if "function" in categories:
            main.extend(
                [
                    'resource "google_storage_bucket" "functions" {',
                    f'  name                        = "gcf-src-{stable}"',
                    "  location                    = var.region",
                    "  uniform_bucket_level_access = true",
                    "  public_access_prevention    = \"enforced\"",
                    "  force_destroy               = true",
                    "  labels                      = var.labels",
                    "}",
                    "",
                    "# Placeholder Cloud Functions scaffold — package/object must be supplied before apply.",
                    'resource "google_cloudfunctions2_function" "this" {',
                    f'  name        = "fn-{stable}"',
                    "  location    = var.region",
                    "  description = \"Review-candidate function from AWS Lambda mapping\"",
                    "",
                    "  build_config {",
                    '    runtime     = "python312"',
                    '    entry_point = "hello_http"',
                    "    source {",
                    "      storage_source {",
                    "        bucket = google_storage_bucket.functions.name",
                    '        object = "PLACEHOLDER-function-source.zip"',
                    "      }",
                    "    }",
                    "  }",
                    "",
                    "  service_config {",
                    "    max_instance_count = 1",
                    "    available_memory   = \"256M\"",
                    "    timeout_seconds    = 60",
                    "  }",
                    "",
                    "  labels = var.labels",
                    "}",
                    "",
                ]
            )

        if "database_postgres" in categories:
            main.extend(
                [
                    'resource "random_password" "postgres_admin" {',
                    "  length  = 24",
                    "  special = true",
                    "}",
                    "",
                    "# Move root password to Secret Manager before production apply.",
                    'resource "google_sql_database_instance" "this" {',
                    f'  name             = "psql-{stable}"',
                    '  database_version = "POSTGRES_15"',
                    "  region           = var.region",
                    "",
                    "  settings {",
                    f'    tier = {hcl_string(sku.get("cloudsql_tier") or "db-f1-micro")}',
                    "    user_labels = var.labels",
                    "    ip_configuration {",
                    "      ipv4_enabled    = false",
                    "      private_network = google_compute_network.this.id",
                    "    }",
                    "  }",
                    "",
                    "  root_password = random_password.postgres_admin.result",
                    "",
                    "  deletion_protection = false",
                    "}",
                    "",
                ]
            )

        if "queue" in categories or "event" in categories:
            main.extend(
                [
                    'resource "google_pubsub_topic" "primary" {',
                    f'  name   = "topic-{stable}"',
                    "  labels = var.labels",
                    "}",
                    "",
                    'resource "google_pubsub_subscription" "primary" {',
                    f'  name  = "sub-{stable}"',
                    "  topic = google_pubsub_topic.primary.name",
                    "  labels = var.labels",
                    "}",
                    "",
                ]
            )

        if "load_balancer" in categories:
            if not needs_network:
                main.extend(
                    [
                        'resource "google_compute_network" "this" {',
                        f'  name                    = "vpc-{group_id[:55]}"',
                        "  auto_create_subnetworks = false",
                        "}",
                        "",
                        'resource "google_compute_subnetwork" "default" {',
                        '  name          = "subnet-default"',
                        "  ip_cidr_range = var.subnet_cidr",
                        "  region        = var.region",
                        "  network       = google_compute_network.this.id",
                        "  private_ip_google_access = true",
                        "}",
                        "",
                    ]
                )
            main.extend(
                [
                    'resource "google_compute_address" "lb" {',
                    f'  name   = "pip-lb-{stable}"',
                    "  region = var.region",
                    "  labels = var.labels",
                    "}",
                    "",
                    'resource "google_compute_region_health_check" "this" {',
                    f'  name   = "hc-{stable}"',
                    "  region = var.region",
                    "",
                    "  tcp_health_check {",
                    "    port = 80",
                    "  }",
                    "}",
                    "",
                    'resource "google_compute_region_backend_service" "this" {',
                    f'  name                  = "bes-{stable}"',
                    "  region                = var.region",
                    '  protocol              = "TCP"',
                    '  load_balancing_scheme = "EXTERNAL"',
                    "  health_checks         = [google_compute_region_health_check.this.id]",
                    "}",
                    "",
                    'resource "google_compute_forwarding_rule" "this" {',
                    f'  name                  = "fr-{stable}"',
                    "  region                = var.region",
                    '  ip_protocol           = "TCP"',
                    '  load_balancing_scheme = "EXTERNAL"',
                    "  port_range            = \"80\"",
                    "  ip_address            = google_compute_address.lb.id",
                    "  backend_service       = google_compute_region_backend_service.this.id",
                    "  labels                = var.labels",
                    "}",
                    "",
                ]
            )

        if "static_ip" in categories and "load_balancer" not in categories:
            main.extend(
                [
                    'resource "google_compute_address" "this" {',
                    f'  name   = "pip-{stable}"',
                    "  region = var.region",
                    "  labels = var.labels",
                    "}",
                    "",
                ]
            )

        if "database_nosql" in categories:
            main.extend(
                [
                    "# Review-candidate Bigtable scaffold for DynamoDB-class workloads.",
                    'resource "google_bigtable_instance" "this" {',
                    f'  name = "bt-{stable}"',
                    "",
                    "  cluster {",
                    f'    cluster_id   = "bt-{stable}-c1"',
                    "    zone         = \"${var.region}-a\"",
                    "    num_nodes    = 1",
                    '    storage_type = "SSD"',
                    "  }",
                    "",
                    "  labels = var.labels",
                    "",
                    "  deletion_protection = false",
                    "}",
                    "",
                    'resource "google_bigtable_table" "primary" {',
                    '  name          = "primary"',
                    "  instance_name = google_bigtable_instance.this.name",
                    "",
                    "  column_family {",
                    '    family = "cf1"',
                    "  }",
                    "}",
                    "",
                ]
            )

        google_resource_counts = _google_resource_type_counts_in_main(main)
        google_types = set(google_resource_counts)
        group_google_types[group_id] = google_types
        group_google_type_counts[group_id] = google_resource_counts
        if not google_types:
            main.append("# No full GCP resource scaffold for this group's categories.")
            main.append("# See mapping-decisions.json emission fields and gcp/artifacts/review-needed.md.")
            main.append("")

        decisions_path = root / "mapping-decisions.json"
        decisions_path.write_text(json.dumps(group, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        write_file(root / "main.tf", "\n".join(main))
        write_file(
            root / "outputs.tf",
            """
      output "project_id" {
        value = var.project_id
      }

      output "migration_group_id" {
        value = var.labels["migration_group"]
      }
    """,
        )

        rows = [
            "| AWS type | GCP target | Default resource | Status | Emission | Confidence | Review note |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for decision in group["mapping_decisions"]:
            default_target = decision.get("default_target") or "-"
            status = decision.get("status", "mapped")
            emission = decision.get("emission") or "-"
            svc = decision.get("gcp_service") or decision.get("azure_service") or "-"
            rows.append(
                f"| `{decision['source_type']}` | {svc} | `{default_target}` | {status} | `{emission}` | `{decision['confidence']}` | {decision['review']} |"
            )
        write_file(
            root / "README.md",
            f"""
      # GCP migration root: {group_id}

      Review-candidate root from `aws/groups/{group_id}/`.
      **Not apply-ready** until placeholders and review-needed items are resolved.

      ## Mapping Decisions

      {chr(10).join(rows)}

      ## Validation

      `tofu init -backend=false && tofu fmt -check && tofu validate && tofu plan`
      (live plan needs read-capable GCP credentials; never apply from this workflow).
    """,
        )

        mapping_decisions[group_id] = group
        summary_groups.append(
            {
                "group_id": group_id,
                "source_resource_counts": {
                    "aws_cloudwatch_log_group": logging_emission.get("source_count", 0)
                } if "observability" in categories else {},
                "generated_resource_counts": {
                    "google_logging_project_bucket_config": logging_emission.get("emitted_count", 0)
                } if "observability" in categories else {},
                "logging_source_inventory_available": logging_emission.get("source_inventory_available") if "observability" in categories else None,
                "logging_retention_assumption_count": logging_emission.get("assumption_count", 0),
                "logging_routing_status": logging_emission.get("routing_status"),
                "logging_mappings": logging_emission.get("mappings", []),

                "root": f"gcp/groups/{group_id}",
                "categories": sorted(categories),
                "emissions": sorted(emissions),
                "google_resource_types": sorted(google_types),
                "confidence": group["confidence"],
                "review_needed": group["review_needed"],
                "review_needed_reason": group.get("review_needed_reason"),
                "review_needed_reasons": group.get("review_needed_reasons") or [],
            }
        )

    write_file(
        gcp_root / ".gitignore",
        """
      **/.terraform/
      **/.terraform.lock.hcl
      **/*.tfplan
      **/gcp.tfplan
      **/*.out
      **/crash.log
      **/crash.*.log
      **/*.tfstate
      **/*.tfstate.*
      # mktemp leftovers from interrupted validate (final file is validation-report.json)
      artifacts/validation-report.*
      !artifacts/validation-report.json
    """,
    )

    conversion = _compute_infra_conversion(work, group_google_types, group_decisions_by_id, group_google_type_counts)

    (artifacts / "mapping-decisions.json").write_text(
        json.dumps(mapping_decisions, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (artifacts / "generation-summary.json").write_text(
        json.dumps(
            {
                "generated_group_count": len(summary_groups),
                "groups": summary_groups,
                "mode": profile.get("mode") or "review_candidate",
                "standards": [
                    "gcp-cloud-naming",
                    "private-by-default-storage",
                    "opentofu-hashicorp-root-layout",
                    "honest-emission-labels",
                    "source-instance-coverage-gate-0.90",
                ],
                "emission_counts": emission_counts,
                "source_reconciliation": reconciliation,
                "mapping_catalog": profile.get("mapping_catalog", {}),
                **{k: conversion[k] for k in (
                    "infra_eligible_count",
                    "infra_converted_count",
                    "infra_conversion_rate",
                    "infra_conversion_ok",
                    "identity_scaffold_count",
                    "app_iam_eligible_count",
                    "app_iam_converted_count",
                    "app_iam_conversion_rate",
                    "app_iam_conversion_ok",
                    "infra_conversion_gaps",
                    "source_coverage_applicable_count",
                    "source_coverage_converted_count",
                    "source_coverage_rate",
                    "source_coverage_threshold",
                    "source_coverage_ok",
                    "source_non_applicable_count",
                    "source_unsupported_count",
                    "source_instance_count",
                    "app_iam_conversion_threshold",
                )},
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    write_file(
        gcp_root / "README.md",
        """
  # GCP destination IaC (review candidate)

  Generated by StackGen after AWS reverse-IaC validation.

  ## Standards

  - Google Cloud naming (`vpc-`, `subnet-`, `gcs-`, `sa-`, `gke-`, ...)
  - Private-by-default storage (uniform bucket-level access, public access prevention)
  - OpenTofu/HashiCorp root layout per group; runtime logs/plans gitignored
  - Catalog `emission` field tells you what was actually generated vs documented
  - Source-instance coverage rate counts converted applicable AWS instances (infra + app-IAM) against all applicable source instances; target ≥ 90%.
  - Coverage rate is `null` when no applicable instances exist; that is not a passing coverage gate.
  - Explicit non-applicable instances are reported separately; unknown/unsupported instances remain in the denominator and count as uncovered.
  - App IAM conversion: workload roles/custom policies → SA + custom role + binding (acquisition path)

  ## Layout

  - `groups/<group_id>/` — Terraform roots
  - `artifacts/` — blueprint, mapping decisions, validation report, review-needed
  - `.gitignore` — excludes `*.out`, `.terraform`, plans, state

  This workflow never applies GCP resources.
""",
    )

    return {
        "generated_group_count": len(summary_groups),
        "emission_counts": emission_counts,
        **conversion,
    }


def main(argv=None):
    argv = argv or sys.argv[1:]
    work = Path(argv[0] if argv else ".")
    result = generate(work)
    print(f"gcp_iac_group_count={result['generated_group_count']}")
    print(f"gcp_emission_counts={json.dumps(result['emission_counts'], sort_keys=True)}")
    print(f"gcp_infra_eligible_count={result.get('infra_eligible_count', 0)}")
    print(f"gcp_infra_converted_count={result.get('infra_converted_count', 0)}")
    print(f"gcp_infra_conversion_rate={result.get('infra_conversion_rate', 0)}")
    print(f"gcp_infra_conversion_ok={str(result.get('infra_conversion_ok', False)).lower()}")
    print(f"gcp_source_coverage_rate={result.get('source_coverage_rate', 0)}")
    print(f"gcp_source_coverage_ok={str(result.get('source_coverage_ok', False)).lower()}")
    print(f"gcp_identity_scaffold_count={result.get('identity_scaffold_count', 0)}")
    print(f"gcp_app_iam_eligible_count={result.get('app_iam_eligible_count', 0)}")
    print(f"gcp_app_iam_converted_count={result.get('app_iam_converted_count', 0)}")
    print(f"gcp_app_iam_conversion_rate={result.get('app_iam_conversion_rate', 0)}")
    print(f"gcp_app_iam_conversion_ok={str(result.get('app_iam_conversion_ok', False)).lower()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
